import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getDb } from '$lib/server/db';
import { getConsumer } from '$lib/server/identity/consumers';
import { mintReset } from '$lib/server/identity/password-reset';
import { logAccess } from '$lib/server/identity/access-log';

export const POST: RequestHandler = async ({ request, locals }) => {
  if (!locals.user) throw error(401, 'Unauthorized');
  const db = getDb();
  let b: { id?: number };
  try { b = await request.json(); } catch { throw error(400, 'Invalid JSON body'); }
  const id = Number(b.id);
  if (!getConsumer(db, id)) throw error(404, 'No such user');
  const { token, expiresAt } = mintReset(db, id);
  logAccess(db, { consumerId: id, type: 'password_reset', detail: 'link generated by admin' });
  return json({ link: `/app/reset/${token}`, expiresAt });
};
